server:
  port: 8082

spring:
  application:
    name: "elements-provider-service"
  data:
    mongodb:
      authentication-database: admin
      database: elements_db
      host: localhost
      port: 27017
      username: root
      password: example