server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: designs-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/design-details, /api/design-details/*
        - id: elements-provider-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/element_group
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cloud-ui-three
          jwk-set-uri: http://localhost:8080/realms/cloud-ui-three/protocol/openid-connect/certs

