version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    restart: always
    volumes:
      - ./local/dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  dynamodb_ui:
    image: aaronshaf/dynamodb-admin
    ports:
      - "9000:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=eu-central-1
    depends_on:
      - dynamodb