server:
  port: 8080

spring:
  application:
    name: designs-service

aws:
  dynamodb:
    endpoint: http://localhost:8000
    accessKey: localstack
    secretKey: localstack
    tableName: "DesignDetails"
    indexName: "UserIdIndex"